"""
Pipeline ML — Kepler v7.
Ejecución: python -m ml_pipeline.train --csv <ruta_al_csv>
"""

from ml_pipeline.config import (
    TARGET_NAME,
    ALL_CSV_FEATURES,
    FUNNEL_FEATURES,
    MACRO_FEATURES,
    WEIGHTED_PIPELINE_VARIABLES,
    CONVERSION_CYCLE_WEIGHTS,
    COMPUTED_FEATURE_NAMES,
    FUNNEL_INFORMATIVO,
    PIPELINE_AUTOREG,
    NON_ACTIONABLE_FEATURES,
    MULTICOLLINEARITY_THRESHOLD,
    CSV_DELIMITER,
    INITIAL_TRAIN_WEEKS,
    TARGET_CLIP_PERCENTILE,
    ANOMALY_JUMP_PCT,
    OPTUNA_N_TRIALS,
    OPTUNA_MAX_DEPTH_RANGE,
    OPTUNA_REG_ALPHA_RANGE,
    OPTUNA_NUM_BOOST_ROUND_RANGE,
    LOSS_OBJECTIVE,
    BENCHMARK_WINDOW_WEEKS,
)

__all__ = [
    "TARGET_NAME",
    "ALL_CSV_FEATURES",
    "FUNNEL_FEATURES",
    "MACRO_FEATURES",
    "WEIGHTED_PIPELINE_VARIABLES",
    "CONVERSION_CYCLE_WEIGHTS",
    "COMPUTED_FEATURE_NAMES",
    "FUNNEL_INFORMATIVO",
    "PIPELINE_AUTOREG",
    "NON_ACTIONABLE_FEATURES",
    "MULTICOLLINEARITY_THRESHOLD",
    "CSV_DELIMITER",
    "INITIAL_TRAIN_WEEKS",
    "TARGET_CLIP_PERCENTILE",
    "ANOMALY_JUMP_PCT",
    "OPTUNA_N_TRIALS",
    "OPTUNA_MAX_DEPTH_RANGE",
    "OPTUNA_REG_ALPHA_RANGE",
    "OPTUNA_NUM_BOOST_ROUND_RANGE",
    "LOSS_OBJECTIVE",
    "BENCHMARK_WINDOW_WEEKS",
]
